version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: interview-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: interview_management
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - interview-network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: interview-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - interview-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: interview-backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: interview_management
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-secret-key-change-this
      FRONTEND_URL: http://localhost:3000
    ports:
      - '3001:3001'
    depends_on:
      - mysql
      - redis
    networks:
      - interview-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: interview-frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - interview-network

volumes:
  mysql_data:
  redis_data:

networks:
  interview-network:
    driver: bridge

